"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { cities } from "@/data/cities";
import { probeStorage, readMirror, readRecords, readStates, saveRecords, saveStates, writeMirror } from "@/lib/storage";
import type { City, CityState, Photo, TravelRecord } from "@/lib/types";

type Feature = { geometry: { type: string; coordinates: number[][][] | number[][][][] } };
const project = ([lon, lat]: number[]) => [((lon - 73) / 62) * 1000, ((54 - lat) / 38) * 620];
const ringPath = (ring: number[][]) => ring.map((p, i) => `${i ? "L" : "M"}${project(p).join(" ")}`).join(" ") + "Z";
const pathFor = (feature: Feature) => {
  const polygons = feature.geometry.type === "Polygon" ? [feature.geometry.coordinates as number[][][]] : feature.geometry.coordinates as number[][][][];
  return polygons.map(poly => poly.map(ringPath).join(" ")).join(" ");
};
const cityPoint = (city: City) => project([city.longitude, city.latitude]);
const MAX_PHOTO_DIM = 1600; // 超过此尺寸的图片等比缩放，避免 base64 撑爆移动端 localStorage 配额
const KEEP_RAW_BYTES = 400_000; // 约 400KB 以下的小图原样保留，避免无谓重编码
const resizePhoto = (dataUrl: string, done: (url: string) => void) => {
  const img = new Image();
  img.onload = () => {
    const big = Math.max(img.naturalWidth, img.naturalHeight) > MAX_PHOTO_DIM || dataUrl.length > KEEP_RAW_BYTES;
    if (!big) return done(dataUrl);
    const scale = Math.min(1, MAX_PHOTO_DIM / Math.max(img.naturalWidth, img.naturalHeight));
    const c = document.createElement("canvas");
    c.width = Math.round(img.naturalWidth * scale); c.height = Math.round(img.naturalHeight * scale);
    const ctx = c.getContext("2d"); if (!ctx) return done(dataUrl);
    ctx.drawImage(img, 0, 0, c.width, c.height);
    done(c.toDataURL("image/jpeg", 0.82));
  };
  img.onerror = () => done(dataUrl); // 解码失败时退回原图
  img.src = dataUrl;
};
/** 非 https 环境（如局域网 IP）没有 crypto.randomUUID，提供降级，避免保存静默失败。 */
const newId = () => (typeof crypto !== "undefined" && "randomUUID" in crypto ? crypto.randomUUID() : `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`);
const VISITS = "xingji-visits"; // cookie 访问计数：与 localStorage 不同通道，用于检测 localStorage 被环境清空
const readVisits = () => { try { const m = document.cookie.match(new RegExp(`(?:^|;\\s*)${VISITS}=(\\d+)`)); return m ? parseInt(m[1], 10) : 0; } catch { return 0; } };
const bumpVisits = () => { const v = readVisits() + 1; try { document.cookie = `${VISITS}=${v}; max-age=31536000; path=/; SameSite=Lax`; } catch { /* 忽略 */ } return v; };

export default function Home() {
  const [features, setFeatures] = useState<Feature[]>([]);
  const [records, setRecords] = useState<TravelRecord[]>([]);
  const [states, setStates] = useState<CityState[]>([]);
  const [selected, setSelected] = useState<City | null>(null);
  const [view, setView] = useState<"map" | "timeline" | "stats" | "album">("map");
  const [editor, setEditor] = useState(false);
  const [editing, setEditing] = useState<TravelRecord | null>(null);
  const [confirming, setConfirming] = useState<TravelRecord | null>(null);
  const [saveError, setSaveError] = useState("");
  const [storageLost, setStorageLost] = useState(false);
  const [query, setQuery] = useState("");
  const [lightbox, setLightbox] = useState<Photo[] | null>(null);
  const [photoIndex, setPhotoIndex] = useState(0);
  const [mapTransform, setMapTransform] = useState({ x: 0, y: 0, scale: 1 });
  const canvas = useRef<SVGSVGElement>(null);
  const drag = useRef<{ x: number; y: number; originX: number; originY: number } | null>(null);

  useEffect(() => { fetch("/china-provinces.geojson").then(r => r.json()).then(d => setFeatures(d.features || [])); const recs = readRecords(); const sts = readStates(); setRecords(recs); setStates(sts); const persistent = probeStorage(); const visits = bumpVisits(); const mirror = readMirror(); const lost = (!persistent && visits > 1 && recs.length === 0) || (mirror > 0 && recs.length === 0); setStorageLost(lost); console.log("[xingji:diagnose]", { visits, storagePersistent: persistent, mirrorCount: mirror, recordsLoaded: recs.length, statesLoaded: sts.length, dataLost: lost, url: location.href, ua: navigator.userAgent }); }, []);
  const cityRecords = useMemo(() => selected ? records.filter(r => r.cityId === selected.id).sort((a,b) => a.startDate.localeCompare(b.startDate)) : [], [selected, records]);
  const visitedIds = useMemo(() => new Set(records.map(r => r.cityId)), [records]);
  const plannedIds = useMemo(() => new Set(states.filter(s => s.planned).map(s => s.cityId)), [states]);
  const allPhotos = records.flatMap(r => r.photos ?? []);
  const stats = { cities: visitedIds.size, totalCities: cities.length, provinces: new Set(cities.filter(c => visitedIds.has(c.id)).map(c => c.province)).size, trips: records.length, photos: allPhotos.length, days: records.reduce((sum,r) => sum + Math.max(1, Math.round((new Date(r.endDate).getTime()-new Date(r.startDate).getTime())/86400000)+1),0) };
  const select = (city: City) => { const [x,y]=cityPoint(city); const scale=1.65; setMapTransform({x:500-x*scale,y:310-y*scale,scale}); setSelected(city); setEditor(false); setEditing(null); setConfirming(null); setView("map"); };
  const togglePlan = () => { if (!selected) return; const next = states.filter(s => s.cityId !== selected.id); if (!plannedIds.has(selected.id)) next.push({cityId:selected.id, planned:true}); if (!saveStates(next)) { alert("保存失败：浏览器存储空间不足，请删除部分照片后重试。"); return; } setStates(next); };
  const saveRecord = (record: TravelRecord) => { const next = editing ? records.map(r => r.id === editing.id ? record : r) : [...records, record]; if (!saveRecords(next)) { console.warn("[xingji:save] FAILED，bytes=", JSON.stringify(next).length); setSaveError("保存失败：浏览器存储空间不足。请删除部分照片，或换用体积更小的图片后重试。"); return; } writeMirror(next.length); console.log("[xingji:save] ok, records=", next.length, "bytes=", JSON.stringify(next).length); setRecords(next); setSaveError(""); setEditor(false); setEditing(null); };
  const deleteRecord = (id: string) => { const next = records.filter(r => r.id !== id); if (!saveRecords(next)) { console.warn("[xingji:delete] FAILED"); alert("删除失败：无法写入浏览器存储，记录已保留。"); return; } writeMirror(next.length); setRecords(next); setConfirming(null); };
  const found = query.trim() ? cities.filter(c => `${c.name}${c.province}`.includes(query.trim())).slice(0,6) : [];

  return <main>
    {storageLost && <div className="storage-warning"><span>⚠ 检测到当前浏览环境无法长期保存数据（无痕模式 / 微信内置浏览器 / “退出时清除数据”设置）。本次记录在退出后可能丢失，建议改用系统浏览器普通模式打开。</span><button aria-label="关闭提示" onClick={()=>setStorageLost(false)}>×</button></div>}
    <header><div className="brand"><span>行迹</span><small>XINGJI / CHINA ATLAS</small></div><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索城市或省份" />{found.length>0 && <div className="results">{found.map(c=><button key={c.id} onClick={()=>{select(c);setQuery("")}}><b>{c.name}</b><small>{c.province}</small></button>)}</div>}</div><nav>{([ ["map","地图"],["stats","我的足迹"],["timeline","时间线"],["album","相册"] ] as const).map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{label}</button>)}</nav></header>
    {view === "map" && <section className="map-layout"><div className="map-stage"><div className="map-caption"><p>我的中国旅行地图</p><span>每一处抵达，都是一段私人档案。</span></div><div className="map-controls"><button aria-label="放大地图" onClick={()=>setMapTransform(t=>({...t,scale:Math.min(2.5,t.scale+0.2)}))}>＋</button><button aria-label="缩小地图" onClick={()=>setMapTransform(t=>({...t,scale:Math.max(1,t.scale-0.2)}))}>−</button><button onClick={()=>setMapTransform({x:0,y:0,scale:1})}>重置</button></div><svg ref={canvas} viewBox="0 0 1000 620" aria-label="中国旅行地图" onWheel={e=>{e.preventDefault();setMapTransform(t=>({...t,scale:Math.min(2.5,Math.max(1,t.scale+(e.deltaY<0?0.15:-0.15)))}))}} onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY,originX:mapTransform.x,originY:mapTransform.y};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const d=drag.current;if(!d)return;const rect=e.currentTarget.getBoundingClientRect();const x=d.originX+(e.clientX-d.x)*1000/rect.width;const y=d.originY+(e.clientY-d.y)*620/rect.height;setMapTransform(t=>({...t,x,y}))}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}><g className="map-content" transform={`translate(${mapTransform.x} ${mapTransform.y}) scale(${mapTransform.scale})`}>{features.map((f,i)=><path key={i} d={pathFor(f)} className="province" />)}{cities.map(city=>{ const [x,y]=cityPoint(city); const visited=visitedIds.has(city.id); const planned=plannedIds.has(city.id); return <g key={city.id} className="marker" aria-label={`${city.name}，${visited?"已去过":planned?"计划去":"未记录"}`} transform={`translate(${x} ${y})`} onClick={()=>select(city)}><circle r={visited?7:planned?5:4} className={visited?"visited":planned?"planned":"empty"}/>{(visited || city.id===selected?.id) && <text x="10" y="4">{city.name.replace("市","")}</text>}</g>})}</g></svg><div className="legend"><i className="dot empty"/> 未记录 <i className="dot planned"/> 计划去 <i className="dot visited"/> 已去过</div></div>
      <aside className="side"><Stats stats={stats}/>{selected ? <CityPanel city={selected} records={cityRecords} visited={visitedIds.has(selected.id)} planned={plannedIds.has(selected.id)} onAdd={()=>{setEditing(null);setSaveError("");setEditor(true)}} onPlan={togglePlan} onClose={()=>setSelected(null)} onPhotos={photos=>{setLightbox(photos);setPhotoIndex(0)}} onEdit={r=>{setEditing(r);setSaveError("");setEditor(true)}} onDelete={r=>setConfirming(r)}/> : <div className="welcome"><p className="eyebrow">开始记录</p><h1>这是一张<br/>属于你的中国。</h1><p>选择地图上的城市，保存抵达的日期、片段与影像。</p></div>}</aside></section>}
    {view === "stats" && <StatsPage stats={stats} visited={visitedIds} />}
    {view === "timeline" && <Timeline records={records} />}
    {view === "album" && <Album records={records} onPhotos={p=>{setLightbox(p);setPhotoIndex(0)}} />}
    {editor && selected && <Editor city={selected} initial={editing} error={saveError} onClose={()=>{setEditor(false);setEditing(null);setSaveError("")}} onSave={saveRecord} />}
    {confirming && <ConfirmDelete record={confirming} onCancel={()=>setConfirming(null)} onConfirm={()=>deleteRecord(confirming.id)} />}
    {lightbox && lightbox.length>0 && <Lightbox photos={lightbox} index={photoIndex} setIndex={setPhotoIndex} onClose={()=>setLightbox(null)} />}
  </main>;
}

function Stats({stats}:{stats:{cities:number;totalCities:number;provinces:number;trips:number;photos:number;days:number}}){return <div className="stats">{[[`${stats.cities} / ${stats.totalCities}`,"已去城市"],[stats.provinces,"去过省份"],[stats.trips,"旅行记录"],[stats.photos,"影像照片"],[stats.days,"旅行天数"]].map(([n,l])=><div key={String(l)}><strong>{n}</strong><span>{l}</span></div>)}</div>}
function CityPanel({city,records,visited,planned,onAdd,onPlan,onClose,onPhotos,onEdit,onDelete}:{city:City;records:TravelRecord[];visited:boolean;planned:boolean;onAdd:()=>void;onPlan:()=>void;onClose:()=>void;onPhotos:(p:Photo[])=>void;onEdit:(r:TravelRecord)=>void;onDelete:(r:TravelRecord)=>void}){return <div className="city-panel"><button className="sheet-close" aria-label="关闭城市详情" onClick={onClose}>×</button><div className="sheet-handle"/><p className="eyebrow">{city.province}</p><h2>{city.name}</h2>{visited?<><div className="status done">● 已去过 · {records.length} 次记录</div><button className="primary" onClick={onAdd}>＋ 添加旅行记录</button><div className="record-list">{records.map(r=><article key={r.id}><time>{r.startDate.replaceAll("-", ".")} — {r.endDate.replaceAll("-", ".")}</time><h3>{r.title}</h3>{r.content&&<p>{r.content}</p>}{(r.places ?? []).length>0&&<div className="places">{(r.places ?? []).map(p=><span key={p}>⌖ {p}</span>)}</div>}{(r.photos ?? []).length>0&&<div className="thumbs">{(r.photos ?? []).map((p,i)=><button key={p.id} onClick={()=>onPhotos(r.photos ?? [])}><img src={p.url} alt={p.caption||`${city.name}照片 ${i+1}`}/></button>)}</div>}<div className="record-actions"><button onClick={()=>onEdit(r)}>编辑记录</button><button className="danger" onClick={()=>onDelete(r)}>删除记录</button></div></article>)}</div></>:<><div className="status">○ {planned?"计划前往":"尚未记录"}</div><p className="empty-copy">这里还没有属于你的旅行片段。</p><button className="primary" onClick={onAdd}>＋ 添加旅行记录</button><button className="quiet" onClick={onPlan}>{planned?"取消计划":"标记为计划"}</button></>}</div>}
function Editor({city,initial,error,onClose,onSave}:{city:City;initial:TravelRecord|null;error:string;onClose:()=>void;onSave:(r:TravelRecord)=>void}){const [title,setTitle]=useState(initial?.title ?? "");const [startDate,setStart]=useState(initial?.startDate ?? "");const [endDate,setEnd]=useState(initial?.endDate ?? "");const [content,setContent]=useState(initial?.content ?? "");const [places,setPlaces]=useState<string[]>((initial?.places ?? []).length>0 ? [...(initial?.places ?? [])] : [""]);const [photos,setPhotos]=useState<Photo[]>([...(initial?.photos ?? [])]);const addPhotos=(files:FileList|null)=>{if(!files)return;Array.from(files).forEach(file=>{const reader=new FileReader();reader.onload=()=>resizePhoto(String(reader.result),url=>setPhotos(p=>[...p,{id:newId(),url,caption:""}]));reader.readAsDataURL(file)})};const submit=(e:React.FormEvent)=>{e.preventDefault();if(!title||!startDate||!endDate)return;onSave({id:initial?.id ?? newId(),cityId:city.id,title,startDate,endDate,content,places:places.filter(Boolean),photos,createdAt:initial?.createdAt ?? new Date().toISOString()})};return <div className="modal"><form className="editor" onSubmit={submit}><button type="button" className="close" onClick={onClose}>×</button><p className="eyebrow">{initial?"编辑旅行记录":"新建旅行记录"} · {city.name}</p><h2>{initial?"更新这段旅程":"留住抵达的那一刻"}</h2><label>旅行标题<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="这段旅行的名字"/></label><div className="dates"><label>开始日期<input required type="date" value={startDate} onChange={e=>setStart(e.target.value)}/></label><label>结束日期<input required type="date" value={endDate} onChange={e=>setEnd(e.target.value)}/></label></div><label>旅行经历<textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="这次旅行发生了什么？"/></label><label>去过的地点</label>{places.map((place,i)=><div className="place-row" key={i}><input value={place} onChange={e=>setPlaces(places.map((p,j)=>j===i?e.target.value:p))} placeholder="输入地点名称"/><button type="button" onClick={()=>setPlaces(places.filter((_,j)=>j!==i))}>移除</button></div>)}<button type="button" className="add-place" onClick={()=>setPlaces([...places,""])}>＋ 添加地点</button><label className="upload">照片<input type="file" accept="image/*" multiple onChange={e=>addPhotos(e.target.files)}/><span>选择照片</span></label>{photos.length>0&&<div className="preview">{photos.map(p=><div key={p.id}><img src={p.url} alt="待上传照片"/><input value={p.caption} onChange={e=>setPhotos(photos.map(x=>x.id===p.id?{...x,caption:e.target.value}:x))} placeholder="照片说明"/><button type="button" aria-label="删除这张照片" onClick={()=>setPhotos(photos.filter(x=>x.id!==p.id))}>×</button></div>)}</div>}{error&&<p className="save-error">{error}</p>}<div className="editor-actions"><button type="button" className="cancel" onClick={onClose}>取消</button><button className="primary submit">{initial?"保存修改":"保存这段旅行"}</button></div></form></div>}
function ConfirmDelete({record,onCancel,onConfirm}:{record:TravelRecord;onCancel:()=>void;onConfirm:()=>void}){return <div className="modal" onClick={onCancel}><div className="confirm" onClick={e=>e.stopPropagation()}><p className="eyebrow">删除旅行记录</p><h2>确定要删除这条旅行记录吗？</h2><p>删除后旅行日期、文字记录和照片将被移除，此操作不可撤销。</p><div className="confirm-actions"><button className="cancel" onClick={onCancel}>取消</button><button className="danger" onClick={onConfirm}>确认删除</button></div></div></div>}
function Timeline({records}:{records:TravelRecord[]}){const ordered=[...records].sort((a,b)=>a.startDate.localeCompare(b.startDate));return <section className="content-page"><p className="eyebrow">MY TRAVEL CHRONICLE</p><h1>我的旅行时间线</h1>{ordered.length===0?<Empty text="第一段旅行会在这里，按真实发生的日期展开。"/>:<div className="timeline">{ordered.map(r=>{const city=cities.find(c=>c.id===r.cityId);return <article key={r.id}><time>{r.startDate}</time><div><p>{city?.province}</p><h2>{city?.name}</h2><h3>{r.title}</h3>{r.content&&<p>{r.content}</p>}</div></article>})}</div>}</section>}
function StatsPage({stats,visited}:{stats:{cities:number;totalCities:number;provinces:number;trips:number;photos:number;days:number};visited:Set<string>}){const provinces=Array.from(new Set(cities.map(c=>c.province))).map(province=>({province,total:cities.filter(c=>c.province===province).length,done:cities.filter(c=>c.province===province&&visited.has(c.id)).length})).sort((a,b)=>b.done-a.done);return <section className="content-page"><p className="eyebrow">MY CHINA FOOTPRINT</p><h1>我的足迹</h1><div className="big-stats"><Stats stats={stats}/></div><h2 className="section-title">省份完成度</h2><div className="progress-list">{provinces.map(p=><div key={p.province}><span>{p.province}</span><i><b style={{width:`${p.done/p.total*100}%`}}/></i><em>{p.done} / {p.total}</em></div>)}</div></section>}
function Album({records,onPhotos}:{records:TravelRecord[];onPhotos:(p:Photo[])=>void}){const items=records.flatMap(r=>(r.photos ?? []).map(p=>({p,r})));return <section className="content-page"><p className="eyebrow">PERSONAL PHOTO ARCHIVE</p><h1>影像档案</h1>{items.length===0?<Empty text="当你在旅行记录中添加照片，它们会组成这里的私人影像墙。"/>:<div className="gallery">{items.map(({p,r})=><button key={p.id} onClick={()=>onPhotos(r.photos)}><img src={p.url} alt={p.caption||"旅行照片"}/><span>{p.caption}</span></button>)}</div>}</section>}
function Empty({text}:{text:string}){return <div className="empty"><span>✦</span><p>{text}</p></div>}
function Lightbox({photos,index,setIndex,onClose}:{photos:Photo[];index:number;setIndex:(n:number)=>void;onClose:()=>void}){const p=photos[index];return <div className="lightbox" onClick={onClose}><button className="close" onClick={onClose}>×</button><button className="prev" onClick={e=>{e.stopPropagation();setIndex((index-1+photos.length)%photos.length)}}>‹</button><figure onClick={e=>e.stopPropagation()}><img src={p.url} alt={p.caption||"旅行照片"}/><figcaption>{p.caption}</figcaption></figure><button className="next" onClick={e=>{e.stopPropagation();setIndex((index+1)%photos.length)}}>›</button></div>}
